# Generated by Django 3.2.3 on 2021-06-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winningrestaurant',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='restaurantmenu',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='restaurantmenuvote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
